library(raster)
rast<-raster(ncol=80,nrow=80)
rast[]<-rnorm(n=ncell(rast))
library(RColorBrewer)
my_pal<- brewer.pal(n = 20, name = "OrRd")
plot(rast,col=my_pal)
rast2<-aggregate(rast,fact=2,fun=mean,expand=FALSE)
rast3<-aggregate(rast2,fact=2,fun=mean,expand=FALSE)
rast4<-aggregate(rast3,fact=2,fun=mean,expand=FALSE)
rast5<-aggregate(rast4,fact=2,fun=mean,expand=FALSE)
rast6<-aggregate(rast5,fact=5,fun=mean,expand=FALSE)
par(mfrow=c(2,3))
plot(rast,col=my_pal)
plot(rast2,col=my_pal)
plot(rast3,col=my_pal)
plot(rast4,col=my_pal)
plot(rast5,col=my_pal)
plot(rast6,col=my_pal)
##############GRAPSE TA KELIA
plot(rast2, addfun = function() text(rast2))
###############
rast<-raster(ncol=10,nrow=10)
rast[]<-rpois(n=ncell(rast),2)
rast2<-aggregate(rast,fact=2,fun=max)
library(RColorBrewer)
library(viridisLite)
vir<-viridis(n=12)
mag<-magma(n=5)
rds<-brewer.pal(6,'Spectral')
par(mfrow=c(1,1))
plot(rast, addfun = function() text(rast),col=vir,xaxt='n',yaxt='n',legend=FALSE)
plot(rast2, addfun = function() text(rast2),col=vir,xaxt='n',yaxt='n',legend=FALSE)

